#!/bin/csh
set cwd = $PWD
set exe = $cwd/elliot

source env

set m = 1
  while ($m <= $n_time_intervals)
    set fname = ${fname_arr[$m]}
    set year_start = $year_start_arr[$m]
    set year_stop = $year_stop_arr[$m]

    set n = 1            
    while ($n <= $n_procs)     
# write set of commands to file submit.pbs
      cp submit.start submit.proc.$m.$n
      echo $exe $tmax_dir $tmin_dir $precip_dir $solar_dir $year_start $year_stop $in_dir $out_dir $fname $n_procs $n>> "submit.proc.$m.$n"
      qsub submit.proc.$m.$n
      @ n = $n + 1
    end

  @ m = $m + 1
end

